project:
  type: book
  output-dir: ../html
  preview:
    navigate: false
    watch-inputs: false

book:
  title: "Mobile WebInterface"
  date: last-modified
  sidebar:
    collapse-level: 3
  chapters:
    - index.qmd
    - part: "User Guide"
      chapters:
        - jobs/jobs.qmd
        - status/status.qmd
    - part: "Developers"
      chapters:
        - mwi/mwi.qmd
        - databases/databases.qmd
        - flows/slots-flow.qmd
        - flows/adc.qmd
        - flows/jobs_flow.qmd

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: show

execute:
  freeze: auto
  engine: julia


# quarto preview . --port 3333
