project:
  type: book
  output-dir: ../doc
  preview:
    navigate: false
    watch-inputs: false

book:
  title: "Mobile WebInterface"
  date: last-modified
  sidebar:
    collapse-level: 3
  chapters:
    - index.qmd
    - part: "Databases"
      chapters:
        - databases/databases.qmd
    - part: "Flows"
      chapters:
        - flows/slots-flow.qmd
        - flows/adc.qmd

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: show

execute:
  freeze: auto

# quarto preview . --port 3333 