---
title: "Mobile WebInterface"
---

# Purpose

Add introductory material for operators and developers.

The intent is a error free operation of the ADU system for 95% of the use cases. For the remaining 5% the expert interface on the laptop can be used. <br>
The mobile web interface is designed to be used on a smartphone, tablet or laptop.

### MWI

Call php `mobile/system/ADU-11e/create_system.php` and I should generate a ADU-11e system with 8 channels. <br>
Location should be $HOME/tmp/sqlite_db_created.

Naming convention has changed to MTH5; sample_freq(uency) is now sampling_rate, and float values are now int (Hz). <br>
site -> station <br>
filter mtx4 -> 4<br>
So watch out please.

## Scope

Understanding the databases structure on an advanced level.


::: {.callout-note}
### MTH5
this new interface already uses the naming conventions of MTH5
 
 - station(s) [string]
 - sample rate(s) [int, Hz]
 - duration(s) [int, s]
 - chopper on/off [int 1, 0] to be understood as LF/HF mode [of the coil]

:::

## Definitions

  - **Sensor**: item "outside" the ADU, e.g. electrode, coil, clamp.
  - **Slot**: the physical slot (connector, MP == multi purpose)<br>
    - E~x~ 0
    - E~y~ 1
    - H~x~ 2
    - H~y~ 3
    - H~z~ 4
    - MP H~x~ 5
    - MP H~y~ 6
    - MP H~z~ 7
  - **Channel**: that is a **(sensor + slot)** = the data stream, e.g. E~x~, E~y~, H~x~, H~y~, H~z~, *MP* H~x~, *MP* H~y~, *MP* H~z~. <br>
  *Channel number must not necessarily be the same as the slot number!* <br> For technical details ref.: [ADC](flows/adc.qmd) and [Slots Flow](flows/slots-flow.qmd).



## Auto Detection

| slot 0 | slot 1 | slot 2 | slot 3 | slot 4 | slot 5 | slot 6 | slot 7 |
|---|---|---|---|---|---|---|---|
| false| false | true | true | true | true | true | true |

The mobile web interface will let you configure **E** 0 & 1, e.g. E~x~, E~y~ of J~x~, J~y~ (currents).<br>
Slots > 1 are detected and treated as **H** (magnetic) by default. <br>



